export const CATEGORIES_TYPE = {
  FETCH_CATEGORIES_STAR: "categories/ FETCH_CATEGORIES_STAR",
  FETCH_CATEGORIES_SUCCESS: "categories/ FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categories/ FETCH_CATEGORIES_FAILED",
};
